# Generated by Django 4.2.1 on 2023-05-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_content_options_alter_module_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="image",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="text",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="video",
            name="owner",
        ),
        migrations.DeleteModel(
            name="Content",
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Text",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
    ]
